config/routes.rb
Rails.application.routes.draw do
root "stores#index"

  resources :stores do
    resources :things
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :things
end

app/models/thing.rb
class Thing < ApplicationRecord
  belongs_to :store
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  
  before_action :set_store, except: [:index, :new, :create]
  def index
    @stores = Store.all
  end

  def show
  end

  def new
    @store = Store.new
    render partial: "form"
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to stores_path
    else 
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    @store = Store.find(params[:id])
    if @store.update(store_params)
    redirect_to stores_path
    else
      render :edit
    end
  end

  def destroy
    @store.destroy
    redirect_to stores_path
  end


    private

    def set_store
      @store = Store.find(params[:id])
    end

    def store_params
      params.require(:store).permit(:name)
    end


end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_store
  before_action :set_thing, only: [:show, :edit, :update, :destroy]
  
  def index
    @things = @store.things
  end

  def show
  end

  def new
    @thing = @store.things.new
    render partial: "form"
  end
  
  def create
    @thing = @store.things.new(thing_params)
    if @thing.save
      redirect_to [@store, @thing]
    else
      render :new
    end
  end
  
  def edit
    # render partial: "form"
  end

  def update
    if @thing.update
      redirect_to store_things_path
    else 
      render :edit
    end
  end

  def destroy
    @thing.destroy
    redirect_to store_things_path
  end

  private
  
    def set_store
      @stores = Store.find(params[:store_id])
    end

    def set_thing
      @thing = Thing.find(params[:id])
    end

    def thing_params
      params.require(:thing).permit(:name, :price, :color)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsHomeworkDay3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stores/_form.html.erb
<h1><%= @store.id ? "Edit Store" : "New Store" %></h1>
<hr />
<%= form_for @store do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true, placeholder: "Name" %>

  <%= f.submit %>

  <%= link_to "Back", stores_path %>
  <% end %> 

app/views/stores/edit.html.erb
<h1>Stores#edit</h1>
<p>Find me in app/views/stores/edit.html.erb</p>

app/views/stores/index.html.erb
<h1>What would you like to shop for?</h1>
<%= link_to "Add a Store?", new_store_path %>
<ul>
  <% @stores.each do |store| %>
  <li><%= link_to store.name, store_path(store) %></li>
    <% end %>
</ul>

app/views/stores/new.html.erb
<h1>New Stores</h1>

app/views/stores/show.html.erb
<h1> <%= @store.name %> </h1>
<hr />
<p> View Your Things do?</p>
  <%= link_to "View Your Choices", store_thing_path(@store) %>
  <br />
  <%= link_to "Edit", edit_store_path(@store) %>
  <br />
  <%= link_to "Delete", store_path(@store), method: :delete %>
  <br />
  <br />
  <br />
  <button><%= link_to "View Stores", stores_path %></button>
  

app/views/things/edit.html.erb
<h1>Things#edit</h1>
<p>Find me in app/views/things/edit.html.erb</p>

app/views/things/index.html.erb
<h1>Click a Thing to View Content</h1>
<hr />
<%= link_to "Create a new Thing", new_store_thing_path(@stores) %>
<ul>
  <% @things.each do |t| %>
    <li><%= link_to t.name, store_thing_path(@store, t) %></li>
    <% end %>
</ul>

app/views/things/new.html.erb
<h1>Things#new</h1>
<p>Find me in app/views/things/new.html.erb</p>

app/views/things/show.html.erb
<h1> <%= things.name %></h1>